services:
  task3_service:
    build:
      context: ../
      dockerfile: docker/Dockerfile.task3service
    expose:
      - '8000'
    env_file:
      - ../.env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    volumes:
      - aitiguru_task_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env
    healthcheck:
      test: nc -z $$DB_HOST $$DB_PORT || exit 1
      interval: 5s
      timeout: 10s
      retries: 3

  nginx:
    build:
      context: .
      dockerfile_inline: |
        FROM nginx:latest
        RUN rm /etc/nginx/conf.d/default.conf 

    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - task3_service

volumes:
  aitiguru_task_postgres_data:
